
trigger: 
 branches:
   include:
     - main

pool: mukhtar12

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Dev'
    backendServiceArm: 'mukhtar service conn1'
    backendAzureRmStorageAccountName: 'mukhtar11'
    backendAzureRmContainerName: 'kitab'
    backendAzureRmKey: 'mukhtar.tfstate'
  displayName: terraform init
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Dev'
    environmentServiceNameAzureRM: 'mukhtar service conn1'
  displayName: terraform plan